home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "hudson.tasks.Maven.xml", dir: "/data/jenkins", file: "hudson.tasks.Maven.xml", mode: "0777" },
  { src: "vip-devops-config.xml", dir: "/data/jenkins/nodes/vip-devops", file: "config.xml", mode: "0777" },
  { src: "vip-eip-config.xml", dir: "/data/jenkins/nodes/vip-eip", file: "config.xml", mode: "0777" },
  { src: "vip-ies-i-config.xml", dir: "/data/jenkins/nodes/vip-ies-i", file: "config.xml", mode: "0777" },
  { src: "vip-ies-m-config.xml", dir: "/data/jenkins/nodes/vip-ies-m", file: "config.xml", mode: "0777" },
  { src: "vip-ies-o-config.xml", dir: "/data/jenkins/nodes/vip-ies-o", file: "config.xml", mode: "0777" },
  { src: "vip-npp-config.xml", dir: "/data/jenkins/nodes/vip-npp", file: "config.xml", mode: "0777" },
  { src: "vip-sso-ipki-config.xml", dir: "/data/jenkins/nodes/vip-sso-ipki", file: "config.xml", mode: "0777" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "ude-tutorials",
    service_name: "ude-tutorials",
    src: "ude-tutorials02-config.xml"
  }
]

jenkins_plugins: [ ]
jenkins_admin_username: admin
jenkins_admin_password: admin
plugins:
  - ssh-slaves
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
  - maven-plugin
  - dashboard-view
  - sonar
  - active-directory
  - global-build-stats
  - jobConfigHistory
  - build-pipeline-plugin
  - wildfly-deployer


plugins_files:
  - ace-editor.hpi
  - ace-editor.hpi
  - active-directory.hpi
  - async-http-client.hpi
  - authentication-tokens.hpi
  - branch-api.hpi
  - build-pipeline-plugin.hpi
  - cloudbees-folder.hpi
  - conditional-buildstep.hpi
  - copyartifact.hpi
  - credentials-binding.hpi
  - credentials.hpi
  - dashboard-view.hpi
  - display-url-api.hpi
  - docker-commons.hpi
  - docker-workflow.hpi
  - durable-task.hpi
  - git-client.hpi
  - git.hpi
  - github-api.hpi
  - github.hpi
  - git-server.hpi
  - global-build-stats.hpi
  - handlebars.hpi
  - icon-shim.hpi
  - jackson2-api.hpi
  - javadoc.hpi
  - jobConfigHistory.hpi
  - jquery-detached.hpi
  - jquery.hpi
  - junit.hpi
  - log-parser.hpi
  - mailer.hpi
  - mapdb-api.hpi
  - matrix-project.hpi
  - maven-plugin.hpi
  - metrics.hpi
  - momentjs.hpi
  - parameterized-trigger.hpi
  - pipeline-build-step.hpi
  - pipeline-graph-analysis.hpi
  - pipeline-input-step.hpi
  - pipeline-milestone-step.hpi
  - pipeline-model-api.hpi
  - pipeline-model-declarative-agent.hpi
  - pipeline-model-definition.hpi
  - pipeline-rest-api.hpi
  - pipeline-stage-step.hpi
  - pipeline-stage-tags-metadata.hpi
  - pipeline-stage-view.hpi
  - plain-credentials.hpi
  - promoted-builds.hpi
  - run-condition.hpi
  - scm-api.hpi
  - script-security.hpi
  - sonar.hpi
  - ssh-credentials.hpi
  - ssh-slaves.hpi
  - structs.hpi
  - subversion.hpi
  - support-core.hpi
  - template-project.hpi
  - token-macro.hpi
  - wildfly-deployer.hpi
  - workflow-aggregator.hpi
  - workflow-api.hpi
  - workflow-basic-steps.hpi
  - workflow-cps-global-lib.hpi
  - workflow-cps.hpi
  - workflow-durable-task-step.hpi
  - workflow-job.hpi
  - workflow-multibranch.hpi
  - workflow-scm-step.hpi
  - workflow-step-api.hpi
  - workflow-support.hpi
