- name: Creating user "{{ uusername }}" with admin access
  user: name={{ uusername }} password={{ upassword |password_hash('sha512') }} groups=root append=yes


#- name: Expiring password for user "{{ uusername }}"
#  shell: chage -d 0 "{{ uusername }}"

 
