home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "vip-devops-config.xml", dir: "/data/jenkins/nodes/vip-devops", file: "config.xml", mode: "0777" },
  { src: "vip-eip-config.xml", dir: "/data/jenkins/nodes/vip-eip", file: "config.xml", mode: "0777" },
  { src: "vip-ies-i-config.xml", dir: "/data/jenkins/nodes/vip-ies-i", file: "config.xml", mode: "0777" },
  { src: "vip-ies-m-config.xml", dir: "/data/jenkins/nodes/vip-ies-m", file: "config.xml", mode: "0777" },
  { src: "vip-ies-o-config.xml", dir: "/data/jenkins/nodes/vip-ies-o", file: "config.xml", mode: "0777" },
  { src: "vip-npp-config.xml", dir: "/data/jenkins/nodes/vip-npp", file: "config.xml", mode: "0777" },
  { src: "vip-sso-ipki-config.xml", dir: "/data/jenkins/nodes/vip-sso-ipki", file: "config.xml", mode: "0777" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "books-ms-ansible",
    service_name: "books-ms-centos",
    src: "service-ansible-config.xml"
  }, {
    name: "books-ms",
    service_name: "books-ms-centos",
    src: "{{ main_job_src }}"
  }, {
    name: "books-ms-multibranch",
    service_name: "books-ms-centos",
    src: "service-workflow-multibranch-config.xml"
  }, {
    name: "books-ms-blue-green",
    service_name: "books-ms-centos",
    src: "service-blue-green-config.xml"
  }, {
    name: "books-ms-swarm",
    service_name: "books-ms-centos",
    src: "service-swarm-config.xml"
  }, {
    name: "service-redeploy",
    service_name: "books-ms-centos",
    src: "{{ service_redeploy_src }}"
  }, {
    name: "books-ms-scale",
    service_name: "books-ms-centos",
    src: "service-scale-config.xml",
    scale: "2",
    time: "45 23 31 12 *"
  }, {
    name: "books-ms-descale",
    service_name: "books-ms-centos",
    src: "service-scale-config.xml",
    scale: "-2",
    time: "15 0 2 1 *"
  }, {
     name: "hardware-notification",
     service_name: "books-ms-centos",
     src: "hardware-notification-config.xml"
  }, {
    name: "go-demo-scale",
    service_name: "go-demo",
    src: "service-scale-df-config.xml",
    scale: "+2",
    time: "45 23 31 12 *"
  }, {
    name: "service-scale",
    service_name: "my-service",
    src: "service-scale-health-config.xml",
    scale: "+1",
  }, {
    name: "go-demo-descale",
    service_name: "go-demo",
    src: "service-scale-df-config.xml",
    scale: "-2",
    time: "15 0 2 1 *"
  }, {
    name: "go-demo-1",
    service_name: "go-demo",
    src: "go-demo-1.xml"
  }, {
    name: "go-demo-2",
    service_name: "go-demo",
    src: "go-demo-2.xml"
  }, {
    name: "go-demo-3",
    service_name: "go-demo",
    src: "go-demo-3.xml"
  }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
