---
# file: tasks/main.yml
# Top-level installer for Oracle JDK.
#

- name: precondition - java_version
  fail: msg="ERROR - required variable 'java_version' missing."
  when: java_version is not defined

- name: precondition - java_subversion
  fail: msg="ERROR - required variable 'java_subversion' missing."
  when: java_subversion is not defined

- name: precondition - java_install_jce
  fail: msg="ERROR - required variable 'java_install_jce' missing."
  when: java_install_jce is not defined

- include: set-role-variables.yml



- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"

- name: copy scripts to server
  copy: src="../files/check-java-version.sh"  dest="{{ java_download_path }}/"  mode="a+x"

- name: check if specific version of Oracle JDK is installed?
  shell: LC_ALL="en_US.UTF-8"  {{ java_download_path }}/check-java-version.sh  "{{ jdk_version }}"
  register: jdk_info
  changed_when: false
  failed_when: jdk_info.rc > 0

#- debug: var=jdk_info

- include: install.yml
  when: (jdk_info.stdout|from_json).not_found

- name: make sure /etc/profile.d exists
  file: path=/etc/profile.d  state=directory
  ignore_errors: yes

- name: export JAVA_HOME
  ignore_errors: yes
  template:
    src:  ../templates/java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: "a+x"

