- name: CentOS dirctory are copied
  file: path=/etc/docker state=directory mode=0755
  ignore_errors: yes
  tags: [docker]

- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [docker]

- name: Install Docker required packages
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  tags: [docker]  

- name: add docker ce repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  register: docker_yum_repo
  tags: [docker]  
  
- name: make yum cache fast
  shell: yum makecache fast
  when: docker_yum_repo.changed
  tags: [docker] 

- name: get docker stable version number
  shell: yum list docker-ce.x86_64  --showduplicates | sort -r |grep  docker-ce-stable  |awk '{print $2}' | awk 'BEGIN{getline;print}'
  register: docker_stable_version  
  tags: [docker] 

- name: CentOS docker package is installed
  yum:
    name: "docker-ce-{{ docker_stable_version.stdout }}"
    state: present
  notify: restart docker
  tags: [docker]

- name: python-pip is present
  yum:
    name: python-pip
    state: present
  tags: [docker]

- name:  update pip
  become: true
  pip:  
    name: pip
    state: latest 
  tags: [docker]

- name: docker-py is present
  pip:
    name: docker-py
    version: 1.10.6
    state: present
  tags: [docker]

- name: CentOS files are present
  template:
    src: "{{ centos_docker_cfg }}"
    dest: "{{ centos_docker_cfg_dest }}"
  register: copy_result
  tags: [docker]

- name: Centos Daemon is reloaded
  command: systemctl daemon-reload
  when: is_systemd is defined
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Centos Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]

- name: DockerUI is running
  docker_container:
    restart_policy: always
    image: uifd/ui-for-docker
    name: dockerui
    ports: 9000:9000
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  when: not skip_ui is defined
  ignore_errors: yes
  tags: [docker]
 
