#- hosts: all
- hosts:  vip-ies-o
#- hosts:   vip-ies-m,vip-ies-i,vip-sso-ipki  
  remote_user: vagrant
  serial: 1
  roles:    
    - common
    - oracle-java-develop
    - jenkins-node
    - maintain-user
    - jboss-common
    - jboss-eap
