---

- name: "{{ jboss_eap_instance_name }} {{ info }} Check existence of the target dir ({{ target_dir }})"
  stat:
    path: "{{ target_dir }}"
  register: conf_00

# Initial creation of the standalone directory
- block:

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy the JBoss EAP standalone directory "
    shell: "cp -Rfp {{ jboss_home }}/standalone {{ target_dir }}; chown {{ jboss.user }}:{{ jboss.group }} -R {{ target_dir }}"
    register: conf_01

#  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy instance specific standalone.conf"
#    copy:
#      remote_src: true
#      owner: "{{ jboss.user }}"
#      group: "{{ jboss.group }}"
#      src: "{{ jboss_home }}/bin/standalone.conf"
#      dest: "{{ jboss_home}}/configuration/standalone.conf"

  - name: export JBOSS_HOME
    template:
       src:  ../templates/jboss_home.sh.j2
       dest: /etc/profile.d/jboss_home.sh
       mode: "a+x"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Create the service directory"
    file:
      path: "{{ jboss_home }}/service"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      state: directory
      mode: "0755"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy init.d script (jboss-as-standalone.sh)"
    copy:
      remote_src: true
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      src: "{{ jboss_home }}/bin/init.d/jboss-eap-rhel.sh"
#     src: "{{ jboss_home }}/bin/jboss-as-standalone.sh"      
      dest: "{{ jboss_home }}/service/jboss-as-standalone.sh"
      mode: "0755"
    when: conf_00.stat.isdir is undefined or conf_00.stat.isdir == False

  - name: "{{ jboss_eap_instance_name }} {{ info }} Update {{ jboss_home }}/mgmt-*.properties"
    lineinfile:
      dest: "{{ item.dest }}"
      line: "{{ item.line }}"
    with_items:
      - { dest: "{{ jboss_home}}/standalone/configuration/mgmt-users.properties", line: "{{ jboss_eap_instance_admin_user }}={{ jboss_eap_instance_admin_password }}" }
      - { dest: "{{ jboss_home }}/standalone/configuration/mgmt-groups.properties", line: "{{ jboss_eap_instance_admin_user}}={{ jboss_eap_instance_admin_groups }}"  }
    register: conf_10

  - name: standalone.xml configuration templates are applied for Debian
    template:
      src: "{{ item.src }}"
      dest: "{{ jboss_home }}/{{ item.dest }}"
    with_items: "{{ standalone_templates }}"


  - name:  jdbc module directories are created
    file:
      path: "{{ jboss_home }}/{{ item.dir }}"
      mode: "0755"
      recurse: yes
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      state: directory
    with_items: "{{ module_configs }}"

  - name: jdbc module configuration
    template:
      src: "{{ item.src }}"
      dest: "{{ jboss_home }}/{{ item.dir }}"
      mode: "0755"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
#     recurse: yes
#      state: directory
    with_items: "{{ module_configs }}"    

 
  - name: microsoft sqlserver jdbc driver
    get_url:
      url: http://central.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
      dest: "{{ jboss_home }}/modules/com/microsoft/main/mssql-jdbc-6.1.0.jre8.jar"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      mode: "0755"

  - name: MySQL jdbc driver
    get_url:
      url: http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar
      dest: "{{ jboss_home }}/modules/com/mysql/main/mysql-connector-java-5.1.41.jar"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      mode: "0755"

  - name: jtds sqlserver jdbc driver
    get_url:
      url: http://central.maven.org/maven2/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.jar
      dest: "{{ jboss_home }}/modules/net/sourceforge/jtds/main/jtds-1.3.1.jar"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      mode: "0755"


