---

- name: "{{ jboss_eap_instance_name }} {{ info }} Check existence of the target dir ({{ target_dir }})"
  stat:
    path: "{{ target_dir }}"
  register: conf_00

# Initial creation of the standalone directory
- block:

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy the JBoss EAP standalone directory "
    shell: "cp -Rfp {{ jboss_home }}/standalone {{ target_dir }}; chown {{ jboss.user }}:{{ jboss.group }} -R {{ target_dir }}"
    register: conf_01

#  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy instance specific standalone.conf"
#    copy:
#      remote_src: true
#      owner: "{{ jboss.user }}"
#      group: "{{ jboss.group }}"
#      src: "{{ jboss_home }}/bin/standalone.conf"
#      dest: "{{ jboss_home}}/configuration/standalone.conf"

  - name: export JBOSS_HOME
    template:
       src:  ../templates/jboss_home.sh.j2
       dest: /etc/profile.d/jboss_home.sh
       mode: "a+x"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Create the service directory"
    file:
      path: "{{ jboss_home }}/service"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      state: directory
      mode: "0755"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy init.d script (jboss-as-standalone.sh)"
    copy:
      remote_src: true
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      src: "{{ jboss_home }}/bin/init.d/jboss-eap-rhel.sh"
#     src: "{{ jboss_home }}/bin/jboss-as-standalone.sh"      
      dest: "{{ jboss_home }}/service/jboss-as-standalone.sh"
      mode: "0755"
    when: conf_00.stat.isdir is undefined or conf_00.stat.isdir == False

  - name: "{{ jboss_eap_instance_name }} {{ info }} Update {{ jboss_home }}/mgmt-*.properties"
    lineinfile:
      dest: "{{ item.dest }}"
      line: "{{ item.line }}"
    with_items:
      - { dest: "{{ jboss_home}}/standalone/configuration/mgmt-users.properties", line: "{{ jboss_eap_instance_admin_user }}={{ jboss_eap_instance_admin_password }}" }
      - { dest: "{{ jboss_home }}/standalone/configuration/mgmt-groups.properties", line: "{{ jboss_eap_instance_admin_user}}={{ jboss_eap_instance_admin_groups }}"  }
    register: conf_10

  - name: Templates are applied for Debian
    template:
      src: "{{ item.src }}"
      dest: "{{ jboss_home }}/{{ item.dest }}"
    with_items: "{{ standalone_templates }}"
    
